sonar.projectKey=moisova_frontend-project-46
sonar.organization=moisova
sonar.sources=.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/coverage/**,**/__tests__/**,**/.github/**,**/*.yml,**/*.yaml,*.md,Makefile,.npmrc,package.json,package-lock.json,eslint.config.js,file1.json,file2.json,sonar-project.properties

sonar.coverage.exclusions=**/__tests__/**,**/.github/**,eslint.config.js,Makefile,.npmrc,package.json,package-lock.json,file1.json,file2.json,sonar-project.properties

sonar.test.exclusions=**/node_modules/**,**/coverage/**