sonar.projectKey=moisova_frontend-project-46
sonar.organization=moisova
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/.*/
sonar.javascript.lcov.reportPaths=coverage/lcov.info