sonar.projectKey=moisova_frontend-project-46
sonar.organization=moisova

sonar.sources=.
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.test.inclusions=**/__tests__/**/*.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/__tests__/**